# Generated by Django 4.0.4 on 2022-09-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bestiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ideology', models.CharField(max_length=50)),
                ('armor_class', models.CharField(max_length=50)),
                ('health_points', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('move_speed', models.CharField(max_length=50)),
                ('languages', models.CharField(max_length=100)),
                ('danger', models.CharField(max_length=50)),
                ('susceptibility', models.CharField(max_length=200)),
                ('strength', models.IntegerField(default=0, verbose_name='strength bonus')),
                ('dexterity', models.IntegerField(default=0, verbose_name='dexterity bonus')),
                ('constitution', models.IntegerField(default=0, verbose_name='constitution bonus')),
                ('intelligence', models.IntegerField(default=0, verbose_name='intelligence bonus')),
                ('wisdom', models.IntegerField(default=0, verbose_name='wisdom bonus')),
                ('charisma', models.IntegerField(default=0, verbose_name='charisma bonus')),
                ('feature_title', models.CharField(max_length=100)),
                ('feature_description', models.TextField()),
                ('action_title', models.CharField(max_length=100)),
                ('action_description', models.TextField()),
                ('about_title', models.CharField(blank=True, max_length=100)),
                ('about_description', models.TextField()),
            ],
        ),
    ]
