# Generated by Django 4.0.4 on 2022-05-18 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
        migrations.RenameModel(
            old_name='Spells',
            new_name='Spell',
        ),
        migrations.AlterModelOptions(
            name='bestiary',
            options={'verbose_name_plural': 'Bestiaries'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='spell',
            options={'verbose_name_plural': 'Spells'},
        ),
    ]
