# Generated by Django 4.0.4 on 2022-05-18 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_rename_items_item_rename_spells_spell_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.bestiary')),
            ],
        ),
    ]
