# Generated by Django 4.1.1 on 2022-09-26 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_topic_delete_bestiary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='subclass',
            field=models.CharField(choices=[('race', 'Race'), ('class', 'Class'), ('items', 'Items'), ('bestiary', 'Bestiary'), ('spells', 'Spells')], max_length=8),
        ),
        migrations.CreateModel(
            name='Bestiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ideology', models.CharField(max_length=50)),
                ('armor_class', models.CharField(max_length=50)),
                ('health_points', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('move_speed', models.CharField(max_length=50)),
                ('languages', models.CharField(max_length=100)),
                ('danger', models.CharField(max_length=50)),
                ('susceptibility', models.CharField(max_length=200)),
                ('strength', models.IntegerField(default=0, verbose_name='strength bonus')),
                ('dexterity', models.IntegerField(default=0, verbose_name='dexterity bonus')),
                ('constitution', models.IntegerField(default=0, verbose_name='constitution bonus')),
                ('intelligence', models.IntegerField(default=0, verbose_name='intelligence bonus')),
                ('wisdom', models.IntegerField(default=0, verbose_name='wisdom bonus')),
                ('charisma', models.IntegerField(default=0, verbose_name='charisma bonus')),
                ('feature_title', models.CharField(max_length=100)),
                ('feature_description', models.TextField()),
                ('action_title', models.CharField(max_length=100)),
                ('action_description', models.TextField()),
                ('about_title', models.CharField(blank=True, max_length=100)),
                ('about_description', models.TextField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.topic')),
            ],
        ),
    ]
