# Generated by Django 4.0.4 on 2022-05-18 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_race'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='race',
            options={'verbose_name_plural': 'Races'},
        ),
        migrations.RenameField(
            model_name='bestiary',
            old_name='about_description',
            new_name='about',
        ),
        migrations.RemoveField(
            model_name='bestiary',
            name='about_title',
        ),
        migrations.RemoveField(
            model_name='bestiary',
            name='action_description',
        ),
        migrations.RemoveField(
            model_name='bestiary',
            name='action_title',
        ),
        migrations.RemoveField(
            model_name='bestiary',
            name='feature_description',
        ),
        migrations.RemoveField(
            model_name='bestiary',
            name='feature_title',
        ),
        migrations.AddField(
            model_name='bestiary',
            name='action',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='wiki.field'),
        ),
        migrations.AddField(
            model_name='bestiary',
            name='feature',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='features', to='wiki.field'),
        ),
    ]
