# Generated by Django 4.0.4 on 2022-05-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_remove_race_title_race_action_race_armor_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='armor_class',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='race',
            name='health_points',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='race',
            name='ideology',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='race',
            name='languages',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='race',
            name='move_speed',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='race',
            name='size',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='race',
            name='susceptibility',
            field=models.CharField(max_length=200),
        ),
    ]
