<<<<<<< HEAD
version: "3.8"

services:
#  web:
#    build: ./DND
#    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - ./DND/:/usr/src/DND/
#    ports:
#      - "8000:8000"
#    env_file:
#      - .env

  db:
    restart: always
    image: postgres:14.2-alpine
    container_name: dnd-postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=DND
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    container_name: dnd-pgadmin
    depends_on:
      - db
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: root
    restart: always

volumes:
=======
version: "3.8"

services:
#  web:
#    build: ./DND
#    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - ./DND/:/usr/src/DND/
#    ports:
#      - "8000:8000"
#    env_file:
#      - .env

  db:
    restart: always
    image: postgres:14.2-alpine
    container_name: dnd-postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    container_name: dnd-pgadmin
    depends_on:
      - db
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: root
    restart: always

volumes:
>>>>>>> 392ded21f4f76be087291ab133ad27a13e296933
  postgres_data: